### ISSUE TITLE
RuntimeError: multiple tensor pointing at the same memory location

### ISSUE THREAD

**Issue by ghost** [monniert/dti-sprites#2]
Hey there! I loved your paper and I'm finding your code quite interesting.

I'm running a training job locally on the Tetrominoes config and dataset and, while first iterations run smoothly, at the end of the epoch I'm finding this error, which seems to stem from the `optimization.step()` line. 

```
Traceback (most recent call last):
  File "src/trainer.py", line 1091, in <module>
    trainer.run(seed=seed)
  File "/home/ubuntu/education/src/dti-sprites/src/utils/__init__.py", line 102, in wrapper
    return f(*args, **kw)
  File "src/trainer.py", line 292, in run
    self.single_train_batch_run(images)
  File "src/trainer.py", line 337, in single_train_batch_run
    self.optimizer.step()
  File "/home/ubuntu/anaconda3/envs/dti-sprites/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 67, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/dti-sprites/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/dti-sprites/lib/python3.7/site-packages/torch/optim/adam.py", line 131, in step
    p.addcdiv_(exp_avg, denom, value=-step_size)
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. 
Please clone() the tensor before performing the operation.
```

Have you had this same issue? Do you know how to solve it? I believe it's caused by a tensor not being called the `clone()` or `expand()` operation.

**Comment by monniert** [comment]
Hi @JHevia23, thanks for reaching out!

I have not encountered this error, and it is weird it is only happening at the end of the epoch and not every iteration... Have you built the conda env following the `readme.md`? If not, could you check that your python packages have the same version as the ones I provided in the `environment.yml`?

Yes the error often means there is an `expand` operation before an in-place operation (here `addcdiv_`); could you get the tensor name or size of `p` that raises the issue so that we identify it?

**Comment by monniert** [comment]
closing the issue since there is no reply, feel free to re-open it!
